apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: zabbix-demo
  namespace: openshift-gitops
  annotations:
    argocd.argoproj.io/sync-wave: "4"
spec:
  project: default
  source:
    repoURL: https://github.com/HugoPfeffer/demo-tcdf.git
    targetRevision: main
    path: argocd/
  destination:
    server: https://kubernetes.default.svc
    namespace: zabbix-demo
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    syncOptions:
      - CreateNamespace=false
